name: openbn
description: "A new Flutter project."

publish_to: 'none' 

version: 1.2.2+21


environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.0.0
  get_storage: ^2.0.3
  firebase_auth: ^5.2.0
  pin_code_fields: ^8.0.1
  firebase_core: ^3.4.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  dio: ^5.4.2+1
  cached_network_image: ^3.3.1
  permission_handler: ^10.4.3
  intl: ^0.19.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.1.2
  share_plus: ^10.0.0
  file_picker: ^5.3.2
  intl_phone_field: ^3.2.0
  firebase_storage: ^12.2.0
  google_places_flutter: ^2.0.8
  path_provider: ^2.0.15
  url_launcher: ^6.3.0
  firebase_remote_config: ^5.1.0
  package_info_plus: ^8.0.2
  connectivity_plus: ^6.0.5
  sms_autofill: ^2.3.1
  fluttertoast: ^8.2.6
  flutter_pdfview: ^1.3.2
  app_links: ^6.1.3
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.26
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_sliders: ^26.2.12
  recase: ^4.1.0
  lottie: ^3.1.2
  fl_chart: ^0.69.0
  flutter_web_auth: ^0.5.0
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  fpdart: ^1.1.0
  shimmer: ^3.0.0
  flashy_tab_bar2: ^0.0.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  showcaseview: ^3.0.0
  image_cropper: ^8.0.2
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lottie/
  fonts: 
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montesserat/Montserrat-Bold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montesserat/Montserrat-Light.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montesserat/Montserrat-Regular.ttf

    # - family: Montserrat-Bold
    #   fonts:
    #     - asset: assets/fonts/Airal/Arial-bold.ttf
    # - family: Montserrat-Light
    #   fonts:
    #     - asset: assets/fonts/Airal/Arial-light.ttf
    # - family: Montserrat-Regular
    #   fonts:
    #     - asset: assets/fonts/Airal/Arial-regular.ttf
