// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTMpKoa6h4sOflFhnpa9uHl-HlUQ0gsk',
    appId: '1:473077239498:android:88565669b4f7442bd9ee33',
    messagingSenderId: '473077239498',
    projectId: 'yohire-a7f13',
    storageBucket: 'yohire-a7f13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSvoK-RMjfIpZHV2io_ctU33B17hphlQ',
    appId: '1:473077239498:ios:fc02385db482a5d2d9ee33',
    messagingSenderId: '473077239498',
    projectId: 'yohire-a7f13',
    storageBucket: 'yohire-a7f13.appspot.com',
    androidClientId: '473077239498-g6h05gub72b8brnt7mq7kam1v0q9k3id.apps.googleusercontent.com',
    iosClientId: '473077239498-vi4s4hh74mo088mo9e3otdrb66fh5hhe.apps.googleusercontent.com',
    iosBundleId: 'com.yohiresoftwares.yohirejobs',
  );

}